sudo: required

services:
- docker

language: bash

script:
# prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t snips-hassio .
  - docker images
  - docker tag snips-hassio $DOCKER_USERNAME/snips-hassio
  - docker push $DOCKER_USERNAME/snips-hassio
