env:
  matrix:  
    - NAME=snips-hassio
      VERSION=$(node -p require('./snips/config.json').version)
      BASE_DIR=snips
    - NAME=rasbian-ssh
      VERSION=$(node -p require('./raspbian/config.json').version)
      BASE_DIR=raspbian

sudo: required

services:
- docker

language: bash

script:
  - cd ./${BASE_DIR}
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ${NAME} .
  - docker images
  - docker tag ${NAME} clemtal/${NAME}:${VERSION}
  - docker push clemtal/${NAME}:${VERSION}
  - docker tag ${NAME} clemtal/${NAME}
  - docker push clemtal/${NAME}
